include: []

variables:
  TEST_REPORT_FILE: report.xml

default:
  tags:
  - dind

image: golang:1.22 # Only for CI testing, not for production run time usage

stages:
  - test
  - build
  - deploy

check:
  stage: test
  script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
  - golangci-lint run

unit-test:
  stage: test
  script:
  - go install gotest.tools/gotestsum@latest
  - make NGC_API_KEY=$NGC_API_KEY TEST_REPORT_FILE=$TEST_REPORT_FILE test
  artifacts:
    when: always
    reports:
      junit: $TEST_REPORT_FILE

# FIXME: Disabled for testing
acceptance-test:
  stage: test
  script:
  - go install gotest.tools/gotestsum@latest
  - make NGC_API_KEY=$NGC_API_KEY TEST_REPORT_FILE=$TEST_REPORT_FILE testacc
  artifacts:
    when: always
    reports:
      junit: $TEST_REPORT_FILE

build:
  stage: build
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  # Don't run when triggered with tag, since the publish step will include build process.
  - if: $CI_COMMIT_TAG !~ "/^$/"
    when: never
  # Prevent branch pipeline, otherwise it would run CI twice, first on the new branch and
  # second on the merge request. We only want to run the CI on the merge request.
  - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
    when: never
  script:
  - go install github.com/goreleaser/goreleaser/v2@latest
  - goreleaser build --snapshot --clean

release:
  stage: deploy
  rules:
  - if: $CI_COMMIT_TAG !~ "/^$/"
  variables:
    ARTIFACTORY_PRODUCTION_USERNAME: svc-backstage-cicd-group
  script:
  - go install github.com/goreleaser/goreleaser/v2@latest
  - goreleaser release --clean
